from __future__ import annotations

"""Stable tool execution error codes."""

from app.schemas.enums.tool import ToolErrorCode


TOOL_NOT_FOUND = str(ToolErrorCode.TOOL_NOT_FOUND)
TOOL_NOT_AVAILABLE_FOR_AGENT = str(ToolErrorCode.TOOL_NOT_AVAILABLE_FOR_AGENT)
MISSING_REQUIRED_ARGUMENT = str(ToolErrorCode.MISSING_REQUIRED_ARGUMENT)
PERMISSION_DENIED = str(ToolErrorCode.PERMISSION_DENIED)
VERIFICATION_FAILED = str(ToolErrorCode.VERIFICATION_FAILED)
HUMAN_APPROVAL_REQUIRED = str(ToolErrorCode.HUMAN_APPROVAL_REQUIRED)
TOOL_TIMEOUT = str(ToolErrorCode.TOOL_TIMEOUT)
TOOL_EXECUTION_EXCEPTION = str(ToolErrorCode.TOOL_EXECUTION_EXCEPTION)
TOOL_RESULT_SCHEMA_INVALID = str(ToolErrorCode.TOOL_RESULT_SCHEMA_INVALID)
MCP_SERVER_UNAVAILABLE = str(ToolErrorCode.MCP_SERVER_UNAVAILABLE)
MCP_TOOL_TIMEOUT = str(ToolErrorCode.MCP_TOOL_TIMEOUT)
MCP_TOOL_ERROR = str(ToolErrorCode.MCP_TOOL_ERROR)
MCP_TOOL_POLICY_DENIED = str(ToolErrorCode.MCP_TOOL_POLICY_DENIED)
